baseurl: /pittsburgh
permalink: pretty
markdown: kramdown
paginate: 5
repo: pittsburgh
github_org: maptime
future: true
maptime:
  chapter: Maptime Pittsburgh
  twitter: MaptimePGH
  #disqus: YOUR DISQUS USERNAME
gems:
  - jekyll-paginate
  - jekyll-feed