baseurl: /pittsburgh
permalink: pretty
markdown: kramdown
paginate: 5
repo: starter
github_org: maptime
future: true
gems: [jekyll-paginate]
maptime:
  chapter: Maptime Pittsburgh
  twitter: MaptimePGH
  #disqus: YOUR DISQUS USERNAME
